# Generated by Django 5.1.4 on 2024-12-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='raqs.empresa'),
        ),
    ]
