# Generated by Django 5.1.4 on 2024-12-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0002_alter_operador_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raqs',
            name='soldador',
        ),
        migrations.AddField(
            model_name='raqs',
            name='solicitacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='raqs.solicitacaocadastrosoldador'),
            preserve_default=False,
        ),
    ]
