# Generated by Django 5.1.4 on 2024-12-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0003_remove_raqs_soldador_raqs_solicitacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raqs',
            options={'verbose_name': 'RAQS', 'verbose_name_plural': 'RAQS'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaocadastrosoldador',
            options={'verbose_name': 'Solicitação de Cadastro de Soldadores', 'verbose_name_plural': 'Solicitações de Cadastro de Soldadores'},
        ),
        migrations.AlterField(
            model_name='soldador',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='ensaio',
            field=models.CharField(choices=[('DOBRAMENTO', 'Dobramento Mecânico'), ('ULTRASSOM', 'Ultrassom')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='gas_protecao',
            field=models.CharField(choices=[('ARGONIO', 'Argônio'), ('ARCO2', 'Ar+CO²'), ('NA', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='posicao_soldagem_progressao',
            field=models.CharField(choices=[('ASCENDENTE', 'Ascendente'), ('DESCENDENTE', 'Descendente'), ('NA', 'N/A')], max_length=25),
        ),
    ]
