# Generated by Django 5.1.4 on 2024-12-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0004_alter_raqs_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaocadastrosoldador',
            old_name='meta_base_espessura',
            new_name='metal_base_espessura',
        ),
    ]
