# Generated by Django 5.1.4 on 2024-12-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0005_rename_meta_base_espessura_solicitacaocadastrosoldador_metal_base_espessura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='metal_base_diametro',
            field=models.IntegerField(blank=True, choices=[(8, '8"'), (2, '2"')], null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='metal_base_espessura',
            field=models.DecimalField(blank=True, choices=[(12.7, '12,7 mm'), (8.7, '8,7 mm')], decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='modo_transferencia',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('CURTO_CIRCUITO', 'Curto Circuito'), ('GLOBULAR', 'Globular'), ('SPRAY', 'Spray')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='posicao_soldagem_progressao',
            field=models.CharField(choices=[('ASCENDENTE', 'Ascendente'), ('DESCENDENTE', 'Descendente'), ('NA', 'N/A')], max_length=25, null=True),
        ),
    ]
