# Generated by Django 5.1.4 on 2024-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0006_alter_solicitacaocadastrosoldador_metal_base_diametro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='gas_protecao',
            field=models.CharField(blank=True, choices=[('ARGONIO', 'Argônio'), ('ARCO2', 'Ar+CO²'), ('NA', 'N/A')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='metal_base_espessura',
            field=models.FloatField(blank=True, choices=[(12.7, '12,7 mm'), (8.7, '8,7 mm')], null=True),
        ),
    ]
