# Generated by Django 5.1.4 on 2024-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0007_alter_solicitacaocadastrosoldador_gas_protecao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='gas_protecao',
            field=models.CharField(blank=True, choices=[('ARGONIO', 'Argônio'), ('ARCO2', 'Ar+CO²'), ('CO2', 'CO²'), ('NA', 'N/A')], max_length=10, null=True),
        ),
    ]
