# Generated by Django 5.1.4 on 2024-12-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0008_alter_solicitacaocadastrosoldador_gas_protecao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldador',
            name='sinete',
        ),
        migrations.AddField(
            model_name='solicitacaocadastrosoldador',
            name='sinete',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
