# Generated by Django 5.1.4 on 2025-01-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0009_remove_soldador_sinete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raqs.empresa'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='soldador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raqs.soldador'),
        ),
    ]
