# Generated by Django 5.1.4 on 2025-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raqs', '0010_alter_solicitacaocadastrosoldador_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensaiomecanicodobramento',
            name='fotos_amostra_4',
            field=models.FileField(default='', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaocadastrosoldador',
            name='f_number',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaocadastrosoldador',
            name='faixa_qualificada',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='consumivel_classificacao',
            field=models.CharField(choices=[('E7018', 'E7018'), ('E6010', 'E6010'), ('E-71T-1', 'E-71T-1'), ('E-309L', 'E-309L'), ('ER-70S-3', 'ER-70S-3'), ('ER-70S-6', 'ER-70S-6'), ('ER-309L', 'ER-309L'), ('ER-308L', 'ER-308L'), ('ER-NiCrFe3', 'ER-NiCrFe3'), ('E-NiCrFe3', 'E-NiCrFe3'), ('ER-NiCrMo3', 'E-NiCrMo3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastrosoldador',
            name='consumivel_spec',
            field=models.CharField(choices=[('SFA_5-1', 'SFA 5.1'), ('SFA_5-4', 'SFA 5.4'), ('SFA_5-9', 'SFA 5.9'), ('SFA_5-14', 'SFA 5.14'), ('SFA_5-11', 'SFA 5.11'), ('SFA_5-18', 'SFA 5.18'), ('SFA_5-20', 'SFA 5.20')], max_length=15),
        ),
    ]
