# Generated by Django 5.1.4 on 2025-03-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0011_ensaiomecanicodobramento_fotos_amostra_4_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CQS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fq_consumivel",
                    models.CharField(
                        choices=[
                            ("1-3", "1 a 3"),
                            ("1-4", "1 a 4"),
                            ("6", "6"),
                            ("34-41-46", "34, 41 a 46"),
                            ("1-5", "1 e 5"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fq_metal_de_base",
                    models.CharField(
                        choices=[
                            ("1-15f-34-41-49", "1 a 15 f, 34, 41 a 49"),
                            ("todos", "TODOS"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "pn_metal_de_base",
                    models.CharField(
                        choices=[("1", "1"), ("3", "3"), ("46", "46"), ("8", "8")],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="solicitacaocadastrosoldador",
            name="f_number",
        ),
        migrations.RemoveField(
            model_name="solicitacaocadastrosoldador",
            name="faixa_qualificada",
        ),
        migrations.AddField(
            model_name="raqs",
            name="teste_visual",
            field=models.CharField(
                choices=[
                    ("Aprovado", "Aprovado"),
                    ("Reprovado", "Reprovado"),
                    ("N/A", "N/A"),
                ],
                default="N/A",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="solicitacaocadastrosoldador",
            name="processo_soldagem",
            field=models.CharField(
                choices=[
                    ("SMAW", "SMAW - Soldagem com eletrodo revestido"),
                    ("GTAW", "GTAW - Soldagem TIG"),
                    ("GMAW", "GMAW - Soldagem MIG"),
                    ("FCAW", "FCAW - Soldagem com arame tubular"),
                ],
                max_length=4,
            ),
        ),
    ]
