# Generated by Django 5.1.4 on 2025-03-21 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0012_cqs_remove_solicitacaocadastrosoldador_f_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacaocadastrosoldador",
            name="cp_number",
        ),
        migrations.AddField(
            model_name="raqs",
            name="cp_number",
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name="raqs",
            name="data",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="raqs",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="raqs.empresa",
            ),
            preserve_default=False,
        ),
    ]
