# Generated by Django 5.1.4 on 2025-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0013_remove_solicitacaocadastrosoldador_cp_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raqs",
            name="status",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
