# Generated by Django 5.1.4 on 2025-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0014_raqs_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacaocadastrosoldador",
            name="modo_transferencia",
        ),
        migrations.AddField(
            model_name="cqs",
            name="modo_transferencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N/A", "N/A"),
                    ("CURTO_CIRCUITO", "Curto Circuito"),
                    ("GLOBULAR", "Globular"),
                    ("SPRAY", "Spray"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
