# Generated by Django 5.1.4 on 2025-03-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0015_remove_solicitacaocadastrosoldador_modo_transferencia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="raqs",
            name="solicitacao",
        ),
        migrations.RemoveField(
            model_name="raqs",
            name="status",
        ),
        migrations.AddField(
            model_name="raqs",
            name="aberto",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="raqs",
            name="solicitacoes",
            field=models.ManyToManyField(
                related_name="raqs", to="raqs.solicitacaocadastrosoldador"
            ),
        ),
    ]
