# Generated by Django 5.1.4 on 2025-03-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0016_remove_raqs_solicitacao_remove_raqs_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="n_raqs",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="raqs",
            name="n_master",
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="raqs",
            name="n_sequencia",
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solicitacaocadastrosoldador",
            name="f_number",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="solicitacaocadastrosoldador",
            name="metal_base_spec",
            field=models.CharField(
                choices=[
                    ("A-36", "A-36 - Chapa AC"),
                    ("A-106", "A-106 - Tubo AC"),
                    ("16MO3", "16MO3 - Tubo AC"),
                    ("B536", "B536 - Chapa Incoloy"),
                    ("A-309", "A-309 - Chapa"),
                    ("A-312", "A-312 - Chapa"),
                ],
                max_length=25,
            ),
        ),
    ]
