# Generated by Django 5.1.4 on 2025-06-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0017_empresa_n_raqs_raqs_n_master_raqs_n_sequencia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ensaiomecanicodobramento",
            name="fotos_amostra_1",
        ),
        migrations.RemoveField(
            model_name="ensaiomecanicodobramento",
            name="fotos_amostra_2",
        ),
        migrations.RemoveField(
            model_name="ensaiomecanicodobramento",
            name="fotos_amostra_3",
        ),
        migrations.RemoveField(
            model_name="ensaiomecanicodobramento",
            name="fotos_amostra_4",
        ),
    ]
