# Generated by Django 5.1.4 on 2025-06-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0018_remove_ensaiomecanicodobramento_fotos_amostra_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raqs",
            name="motivos_reprovacao",
            field=models.CharField(
                blank=True,
                help_text="Motivos da reprovação separados por vírgula",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="raqs",
            name="lista_de_verificacoes",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "1",
                        "1 - Segue as regras básicas, segurança e utiliza corretamente os EPI's básicos e específicos",
                    ),
                    (
                        "2",
                        "2 - Identifica corretamente os equipamentos e acessórios de soldagem apresentados",
                    ),
                    (
                        "3",
                        "3 - Utiliza corretamente os equipamentos e acessórios de soldagem",
                    ),
                    (
                        "4",
                        "4 - Segue corretamente as variáveis de soldagem determinadas na EPS",
                    ),
                    (
                        "5",
                        "5 - Mantém um padrão uniforme e linear das camadas de solda",
                    ),
                    (
                        "6",
                        "6 - Deposita o material em passes uniformes, mantendo um padrão linear",
                    ),
                    (
                        "7",
                        "7 - Face (mordedura, poros, sobreposição, trinca, deposição insuficiente, reforço excessivo, abertura de arco, respingo",
                    ),
                    (
                        "8",
                        "8 - Raiz (mordedura da raiz, falta de penetração, falta de fusão, perfuração, concavidade, penetração excessiva",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
