# Generated by Django 5.1.4 on 2025-06-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0019_raqs_motivos_reprovacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ensaiomecanicodobramento",
            name="realizado",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ensaioultrassom",
            name="realizado",
            field=models.BooleanField(default=True),
        ),
    ]
