# Generated by Django 5.1.4 on 2025-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0020_ensaiomecanicodobramento_realizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ensaiomecanicodobramento",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ensaioultrassom",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
    ]
