# Generated by Django 5.1.4 on 2025-06-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0021_alter_ensaiomecanicodobramento_aprovado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="raqs",
            name="lista_de_verificacoes",
        ),
        migrations.RemoveField(
            model_name="raqs",
            name="motivos_reprovacao",
        ),
        migrations.RemoveField(
            model_name="raqs",
            name="teste_visual",
        ),
        migrations.CreateModel(
            name="TesteVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Aprovado", "Aprovado"),
                            ("Reprovado", "Reprovado"),
                            ("N/A", "N/A"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "motivos_reprovacao",
                    models.CharField(
                        blank=True,
                        help_text="Motivos da reprovação separados por vírgula",
                        max_length=200,
                    ),
                ),
                ("data_teste", models.DateField(auto_now=True)),
                (
                    "solicitacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="raqs.solicitacaocadastrosoldador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teste Visual",
                "verbose_name_plural": "Testes Visuais",
            },
        ),
    ]
