# Generated by Django 5.1.4 on 2025-08-14 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0022_remove_raqs_lista_de_verificacoes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cqs",
            options={
                "verbose_name": "CQS - Certificado de Qualificação de Soldador",
                "verbose_name_plural": "CQS - Certificados de Qualificação de Soldadores",
            },
        ),
        migrations.AddField(
            model_name="cqs",
            name="data_emissao",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cqs",
            name="data_validade",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cqs",
            name="numero",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="cqs",
            name="solicitacao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cqs",
                to="raqs.solicitacaocadastrosoldador",
            ),
        ),
    ]
