# Generated by Django 5.1.4 on 2025-08-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0023_alter_cqs_options_cqs_data_emissao_cqs_data_validade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cqs",
            name="gn_metal_de_base",
            field=models.CharField(
                blank=True, choices=[("1", "1")], max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cqs",
            name="fq_metal_de_base",
            field=models.CharField(
                choices=[
                    ("1-15f-34-41-49", "1 a 15 f, 34, 41 a 49"),
                    ("todos", "TODOS"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cqs",
            name="pn_metal_de_base",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("3", "3"), ("46", "46"), ("8", "8")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaocadastrosoldador",
            name="consumivel_classificacao",
            field=models.CharField(
                choices=[
                    ("E-6010", "E-6010"),
                    ("E-7018", "E-7018"),
                    ("ER-70S3", "ER-70S3"),
                    ("ER-70S6", "ER-70S6"),
                    ("E-71T1", "E-71T1"),
                    ("ER-309L", "ER-309L"),
                    ("ER-308L", "ER-308L"),
                    ("ER-NiCrFe3", "ER-NiCrFe3"),
                    ("E-NiCrFe3", "E-NiCrFe3"),
                    ("E-309L", "E-309L"),
                    ("ER-NiCrMo3", "ER-NiCrMo3"),
                ],
                max_length=10,
            ),
        ),
    ]
