# Generated by Django 5.1.4 on 2025-08-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raqs", "0024_adicionar_gn_metal_de_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raqs",
            name="n_master",
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="raqs",
            name="n_sequencia",
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
